duckdb/duckdb-iceberg

- .github/workflows/Linux.yml
- .github/workflows/MacOS.yml
- .github/workflows/Windows.yml
run-vcpkg was updated and 11.2 is incompatible with our manylinux image
> pin run-vcpkg

- src/include/yyjson.hpp
- src/yyjson/yyjson.cpp
yyjson has had a number of releases since this dependency was vendor into the extension.  Sync it with the up to date version.
> fix: update yyjson vendor dependency

- src/common/utils.cpp
> Use last instance of /data/ and /metadata/ path

- LICENSE
> Update year in license file to 2025

- .github/workflows/MainDistributionPipeline.yml
- .github/workflows/Rest.yml
- Makefile
- extension_config.cmake
- src/iceberg_functions/iceberg_scan.cpp
- vcpkg.json
- bumps vcpkg version
- bumps submodules
- bumps versions in ci
- applies patches
> Prepare for v1.2.0

- src/catalog_api.cpp
- test/sql/local/iceberg_catalog_read.test
add some logging to the IRC requests
> add logging to iceberg catalog api requests

- extension_config.cmake
- src/catalog_api.cpp
- src/iceberg_extension.cpp
- src/include/catalog_api.hpp
- src/storage/irc_table_entry.cpp
- test/sql/cloud/glue/test_direct_keys_glue.test
- test/sql/cloud/glue/test_glue.test
- test/sql/cloud/s3tables/test_direct_keys_s3tables.test
- test/sql/cloud/s3tables/test_s3tables.test
- test/sql/cloud/test_multiple_catalogs.test
> Refactor sql test

- CMakeLists.txt
I checked out `extension-ci-tools` at the right commit and ran make format - it came up with changes.
Which likely explains the merge conflicts on #132
> Fix formatting on CMakeLists

- Makefile
- test/sql/cloud/glue/test_direct_keys_glue.test
For some reason glue is behaving weirdly.
Edit: I think it's a race condition, nothing major
> Attempt to fix cloud tests #2

- src/catalog_api.cpp
- src/iceberg_extension.cpp
Seems like some IO errors snuck into the Repo again. Just removing them
> replace IO exceptions

- test/sql/local/irc/iceberg_catalog_read.test
- test/sql/local/irc/irc_catalog_read_deletes.test
- test/sql/local/irc/test_lakekeeper.test
- test/sql/local/irc/test_lakekeeper_tpch.test
- test/sql/local/irc/test_mutliple_keys.test
- test/sql/local/irc/test_polaris.test
- test/sql/local/irc/test_polaris_tpch.test
- test/sql/local/irc/test_read_empty_table.test
- test/sql/local/irc/test_use.test
> [Dev] Do not ignore `HTTP` errors in tests

- src/iceberg_manifest.cpp
Slight clean up of the internals, this should stop these two from getting out of sync (as was the case in previous PRs)
Looking more closely at this, I see no reason for even having V1 and V2 structs, this was probably a leftover from the `avro-cpp` days, that forced us to keep separate objects for the v1 and v2 avro schemas.
> Deduplicate the `manifest_file` and `manifest_entry` parsing logic for V1 and V2

- scripts/data_generators/tests/schema_evolve_struct_in_list/__init__.py
- scripts/data_generators/tests/schema_evolve_struct_in_list/q00.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q01.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q02.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q03.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q04.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q05.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q06.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q07.sql
- scripts/data_generators/tests/schema_evolve_struct_in_list/q08.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/__init__.py
- scripts/data_generators/tests/schema_evolve_struct_in_map/q00.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q01.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q02.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q03.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q04.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q05.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q06.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q07.sql
- scripts/data_generators/tests/schema_evolve_struct_in_map/q08.sql
- test/sql/local/schema_evolve_struct_in_list.test
- test/sql/local/schema_evolve_struct_in_map.test
This PR adds tests addressing the limitation mentioned in #226
> Schema evolution of STRUCT inside `MAP` / `LIST`

- .github/workflows/PolarisTesting.yml
> [Dev] Fix Polaris CI

- src/iceberg_functions/iceberg_multi_file_list.cpp
- src/include/iceberg_types.hpp
- src/manifest_list_reader.cpp
> [Dev] The `partitions` field of the `manifest_file` is optional, treat missing different from empty

- src/storage/irc_catalog.cpp
This PR fixes #286 and https://github.com/lakekeeper/lakekeeper/issues/1155 (sorry Lakekeeper, we jumped the gun)
> [Dev] Check the response status code for the `/v1/config` endpoint

- extension_config.cmake
- scripts/data_generators/tests/empty_insert/__init__.py
- scripts/data_generators/tests/empty_insert/q00.sql
- scripts/data_generators/tests/empty_insert/q01.sql
- test/sql/local/iceberg_scans/test_read_empty_insert.test
- vcpkg.json
> Empty Table Insert

- src/storage/authorization/oauth2.cpp
> [OAuth2] x-www-form-urlencode the OAuth2 `client_credentials` POST body

- scripts/data_generators/tests/issue_328/__init__.py
- scripts/data_generators/tests/issue_328/q00.sql
- scripts/data_generators/tests/issue_328/q01.sql
- src/iceberg_functions/iceberg_multi_file_list.cpp
- src/iceberg_predicate.cpp
- src/include/iceberg_predicate.hpp
> Support nested columns in `ManifestMatchesFilter`

- src/include/storage/table_update/iceberg_add_snapshot.hpp
- src/manifest_list_reader.cpp
- src/storage/iceberg_transaction_data.cpp
- src/storage/irc_transaction.cpp
- src/storage/table_update/iceberg_add_snapshot.cpp
- test/python/test_spark_read.py
I'm pretty sure this is why Spark has been acting up in the CI, but let's see what CI has to say about it.
> [Dev] Fix timestamps of created snapshots created by INSERT

- src/common/utils.cpp
Detected via adding [[nodiscard]] to relevant filesystem methods
> Iterative reads in IcebergUtils::FileToString

- src/catalog_api.cpp
- src/common/utils.cpp
- src/iceberg_functions/iceberg_multi_file_reader.cpp
- src/iceberg_functions/iceberg_snapshots.cpp
- src/iceberg_functions/iceberg_to_ducklake.cpp
- src/iceberg_manifest.cpp
- src/metadata/iceberg_table_metadata.cpp
- src/storage/authorization/none.cpp
- src/storage/authorization/sigv4.cpp
- src/storage/irc_table_entry.cpp
This PR addresses a few compilation errors and warnings for my local compilation, see inline comments for details.
> Fix compilation and warnings

- .github/workflows/CloudTesting.yml
- scripts/create_s3_insert_table.py
- test/sql/cloud/r2_catalog/test_r2_inserts.test
- test/sql/cloud/s3tables/test_aws_no_request.test
- test/sql/cloud/test_aws_secret_type.test
passing tests here https://github.com/duckdb/duckdb-iceberg/actions/runs/16565409828
> Fix cloud tests script

- src/aws.cpp
- src/catalog_api.cpp
- src/include/aws.hpp
- src/include/storage/authorization/sigv4.hpp
- src/storage/authorization/sigv4.cpp
There was lots of duplicate code in the AWS request process. Decided to clean it up a little bit
> unify aws request code

- src/catalog_api.cpp
- test/sql/cloud/r2_catalog/test_r2_pagination.test
Fixes https://github.com/duckdblabs/duckdb-internal/issues/5763
also closes https://github.com/duckdb/duckdb-iceberg/issues/401
> Add pagination to get tables and to GetSchemas

- src/iceberg_functions/iceberg_to_ducklake.cpp
This PR fixes https://github.com/duckdblabs/duckdb-internal/issues/5908
See comment for clarification.
> IcebergToDucklake: Fix erroneous error

- .github/workflows/MainDistributionPipeline.yml
This we bumped in ducklake, same needs to be done elsewhere.
> Fixup yml: there are no tags, only branch names

- src/catalog_api.cpp
- src/include/catalog_api.hpp
- test/sql/local/irc/inferred_endpoint_from_secret.test
fixes https://github.com/duckdb/duckdb-iceberg/issues/483
fixes https://github.com/duckdblabs/duckdb-internal/issues/5985
> Fall back to Get Request during schema&table verification if response code is 400 or 405

- src/aws.cpp
- src/include/aws.hpp
- src/storage/authorization/sigv4.cpp
- test/sql/cloud/s3tables/test_timeout_aws.test
- test/sql/local/irc/test_tabulario_docker_image.test
fixes https://github.com/duckdb/duckdb-iceberg/issues/476
> Use Httpfs timeout setting for calls to AWS Rest Catalogs

- .github/workflows/MainDistributionPipeline.yml
- src/common/api_utils.cpp
- src/iceberg_extension.cpp
- test/sql/local/irc/other_engines/test_create_table_then_read_with_other_engine.test
Load httpfs whenever there is a request that does not go through the built-in aws client.
Happens on Attach, and on create Iceberg secret
further closes https://github.com/duckdb/duckdb-iceberg/issues/483
> Load httpfs
