.github/workflows/Windows.yml, test/sql/iceberg_metadata.test, test/sql/iceberg_scan.test, test/sql/iceberg_snapshots.test
This error message was a bit overspecified, which fails when integrating the extension with the duckdb CI
=> fix slightly incorrect error message in test

README.md, scripts/test_data_generator/generate_iceberg.py
This will bump iceberg to the newest version 1.4.2 for data generator and improve the documentation for running the iceberg data generator.
At a later stage it might be considered to run this in a docker container this saves the developer the "hassle" of setting up java, scala, python3 and pyspark.
=> Data Generator: bump Iceberg version, improve documentation

src/common/iceberg.cpp, src/common/schema.cpp, src/common/utils.cpp, src/iceberg_functions/iceberg_snapshots.cpp, src/include/yyjson.hpp, src/yyjson/yyjson.cpp
fix: change yyjson comparisions to type rather than tag.
Many comparisons were performed using `yyjson_get_tag()` rather than `yyjson_get_type()`.  The tag can have additional information set using bits beyond just the type, causing these type comparisons to fail and parsing the metadata to fail.
fix: fix the extension to build with current duckdb main branch.
Fix a few `std::move()` calls and a call to `fs.OpenFile()`.
=> Change yyjson_get_tag() to yyjson_get_type() when doing type comparisons.

src/common/iceberg.cpp, src/iceberg_functions/iceberg_metadata.cpp, src/iceberg_functions/iceberg_scan.cpp, src/iceberg_functions/iceberg_snapshots.cpp, src/include/iceberg_metadata.hpp, test/sql/iceberg_metadata.test, test/sql/iceberg_scan.test, test/sql/iceberg_snapshots.test
This intends to address #29 by providing some additional options when finding metadata files to use.
This PR essentially adds two parameters to the iceberg functions:
- `version` - Either a version number of the table to use, or a "hint" filename that should be read to get the latest version.
Default value: `'version-hint.text'` (preserves the previous behavior of looking for a `version-hint.text` file
Examples: `version='12'`: Explicitly load table version 12. `version='my-custom-version-file.txt'`: Use version from `my-custom-file.txt` instead of `version-hint.text`
- `version_name_format` -  comma-delimited list of format strings that should be tried to find the metadata file name based on the supplied or hinted version.
Default value: `'v%s%s.metadata.json,%s%s.metadata.json` (extends …
=> Addresses #29: Support missing version-hint.txt and provide additional options

src/iceberg_functions/iceberg_scan.cpp, test/sql/iceberg_scan_generated_data_0_001.test
Examine the row-counts in the manifest and count how many rows are in the (existing or added) data resp. deletion files.
Use these two counts to pass the new named_parameter "explicit_cardinality" into the generated parquet_scans.
Note that because iceberg is passing in an explicit schema into the parquet_scan, it does not open any file during bind. That means the parquet_scans it generates did not have any cardinality information during query optimization.
That can cause rather bad query plans. This PR (pb/explicit-iceberg-cardinality) fixes that. Note that this PR needs the DuckDB PR pb/explicit-parquet-cardinality that adds the "explicit_cardinality" named_parameter to parquet_scan.
=> exploit iceberg row-count metadata

src/iceberg_extension.cpp
This should fix #84 by changing where the `unsafe_enable_version_guessing` config value is defined to the same function where other new functions are defined. This has been tested by the following:
```
~/duckdb_iceberg$ make test
...
cd
~/$ duckdb -unsigned
D FORCE INSTALL 'duckdb_iceberg/build/release/repository/v1.1.3/linux_amd64/iceberg.duckdb_extension';
D LOAD iceberg;
D .quit
cd ~/duckdb_iceberg/data/iceberg
~/duckdb_iceberg/data/iceberg$ duckdb -unsigned # note this is my system version of duckdb
D LOAD iceberg;
D SET unsafe_enable_version_guessing=true;
D SELECT COUNT() FROM iceberg_scan('lineitem_iceberg_no_hint');
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        51793 │
└──────────────┘
```
=> Fix extension loading issue described in #84

src/common/iceberg.cpp, test/sql/iceberg_metadata.test, test/sql/iceberg_snapshots.test
The IsDirectory check is not supported on HTTPFileSystem. Leaving this check out is fine: the error message `Invalid Input Error: No version was provided and no version-hint could be found` is clear enough I think.
=> remove isdirectory check

src/storage/irc_table_entry.cpp
I was trying the latest Iceberg REST Catalog support and ran into an issue where it was attempting to recreate the secret every time you run a SELECT statement and throwing due to the conflict setting.
This PR is less than ideal--the right solution would be to cache table info and vended credentials to avoid extra API calls--but it allows repeated queries against the same table.
=> Replace internal table secret on conflict

extension_config.cmake, src/catalog_api.cpp, src/iceberg_extension.cpp, src/include/iceberg_types.hpp, src/storage/irc_table_entry.cpp, test/sql/cloud/test_glue.test
- Don't hit global s3 endpoint when reading from a glue catalog. 
- Use the s3tablescatalog name, and not a hardcoded prefix
- Print error message if AWS request fails.
=> Improvements to glue support

src/catalog_api.cpp, src/catalog_utils.cpp, src/common/utils.cpp, src/iceberg_extension.cpp, src/include/catalog_api.hpp, src/include/catalog_utils.hpp, src/include/iceberg_utils.hpp, src/include/storage/irc_catalog.hpp, src/storage/irc_catalog.cpp, src/storage/irc_schema_set.cpp, src/storage/irc_table_entry.cpp, test/sql/cloud/test_glue.test, test/sql/cloud/tpch_on_cloud.test_slow, test/sql/local/iceberg_catalog_read.test, test/sql/local/irc/test_mutliple_keys.test
This moves around some yyjson utils and some iceberg utils so we can cache table entry credentials and the valid config credentials for as long as possible. 
The IRCatalog passed to the GetMetadataCache is no longer const since the IRCatalog owns the cache, which needs to be updated after requests.
This also adds some small sanity checks for AWS glue warehouse
=> Implement some basic caching

src/common/iceberg.cpp, src/storage/irc_schema_entry.cpp
These cause symbol collisions when linking the iceberg extensions into duckdb together with other extensions
=> make functions static

scripts/data_generators/generate_spark_rest/empty_table/q00.sql, src/common/iceberg.cpp, src/iceberg_functions/iceberg_multi_file_reader.cpp, test/sql/local/iceberg_scans/iceberg_scan.test, test/sql/local/irc/test_read_empty_table.test
fixes https://github.com/duckdb/duckdb-iceberg/issues/108
If there are no snapshots, then we are reading from an empty table. Early out from the `InitializeFiles` call so that we can populate the schema and just return.
=> BugFix: Allow read from empty tables

.github/workflows/CodeQuality.yml
The submodule was not being checked out, so it had no `extension-ci-tools` to use in the workflow.
=> Fix Format Check CI

src/catalog_api.cpp, test/sql/local/iceberg_on_tpch.test
The way this catalog works is that we create an S3 secret that should inform the options passed to the scoped secret we create from the `config` of the `LoadTableResult`
```sql
statement ok
CREATE SECRET (
TYPE S3,
KEY_ID 'admin',
SECRET 'password',
ENDPOINT '127.0.0.1:9000',
URL_STYLE 'path',
USE_SSL 0
);
statement ok
ATTACH '' AS my_datalake (
TYPE ICEBERG,
ENDPOINT 'http://127.0.0.1:8181'
);
```
Without this change, `url_style`, `use_ssl`, `endpoint`, etc.. would not be copied over, causing the scan to fail.
=> Fix scanning from the "local" REST catalog we create in CI

src/common/utils.cpp, src/iceberg_functions/iceberg_metadata.cpp, src/iceberg_functions/iceberg_multi_file_reader.cpp, src/iceberg_functions/iceberg_snapshots.cpp, src/include/iceberg_utils.hpp, test/sql/local/version_name_format_error.test
Further down the codepath this is used with `StringUtil::Format` which throws if these requirements aren't met.
=> [Dev] Fix crash with malformed `version_name_format` parameter.

src/catalog_utils.cpp
Ran into this today trying to connect to a fivetran catalog with invalid credentials. If an Api response has an error, there doesn't seem to be a consistent way to retrieve the error message. So for the fivetran iceberg catalog, a failing secret creation statement results in the following message
```
CREATE SECRET fivetransecret_its_exonerate (
TYPE ICEBERG,
CLIENT_ID '94b5736368eca81',
CLIENT_SECRET '49603291bbbf412763544dabf619393',
ENDPOINT 'https://polaris.fivetran.com/api/catalog'
);
Invalid Configuration Error:
Could not get token from https://polaris.fivetran.com/api/catalog/v1/oauth/tokens, captured error message: Invalid field found while parsing field: messag
```
This PR changes this so that the error message is now
```
Could not get token from …
```
=> Throw whole api result as error if there is no error message

test/sql/local/irc/irc_nested_types.test, test/sql/local/nested_types.test
Adding a test to scan the generated table from the `spark-local` and `spark-rest` connections.
=> Add basic tests for the generated `nested_types` table

src/catalog_api.cpp, src/include/storage/irc_catalog.hpp, src/storage/irc_catalog.cpp
Even if `HasCachedValue` returns true, it is possible that `GetCachedValue` still throws an exception because the cached value has expired between the two function calls. 
I also added a mutex to prevent conflicts when the cached value is simultaneously written and read
=> Fixed some race conditions in caching logic

CMakeLists.txt, src/common/iceberg.cpp, src/iceberg_functions/iceberg_multi_file_reader.cpp, src/iceberg_predicate.cpp, src/iceberg_transform.cpp, src/include/iceberg_metadata.hpp, src/include/iceberg_predicate.hpp, src/include/iceberg_predicate_stats.hpp, src/include/iceberg_transform.hpp, src/include/iceberg_types.hpp
This PR paves the way for implementing transforms other than "identity".
We now parse the `transform` into an `IcebergTransform` structure (which parses the modulo for `bucket` and the width for `truncate`)
Adding functors for transforms in the filter matching logic, which has been moved to `iceberg_predicate.cpp`
Also fix a bug where we now properly check the transform type when filtering on the lower+upper bounds of the `data_file`, before we seemed to always assume this used an `identity` transform.
=> Improve predicate transform architecture

src/storage/irc_table_entry.cpp
This PR fixes #231 
We transform the `storage_location` to lowercase so we can find `metadata` without having to deal with different casings, but then we also use this lowercase version in the scope, which is wrong.
=> Use the original `storage_location` instead of the lowercase version

CMakeLists.txt, src/aws.cpp, src/common/utils.cpp, src/iceberg_extension.cpp
This PR takes the learnings from #245 and applies them to `main`
=> [Dev] Remove traces of `aws` includes, `zlib` include, and do not require `aws`/`curl` in WASM builds.

src/aws.cpp, src/storage/authorization/oauth2.cpp, src/storage/irc_catalog.cpp
I set out to bump duckdb because I was worried that https://github.com/duckdb/duckdb/pull/17553 would break the Iceberg MFR again, but it looks like we don't override the touched methods, so that's great
But while I was running our tests I saw an Internal Exception related to DUCKDB_LOG_WARN and DUCKDB_LOG_DEBUG, this PR fixes those, as well as bump duckdb.
=> [Dev] Bump duckdb | `DUCKDB_LOG_WARN` and `DUCKDB_LOG_DEBUG` don't work like they used to anymore

CMakeLists.txt, src/catalog_api.cpp, src/iceberg_functions/iceberg_metadata.cpp, src/iceberg_functions/iceberg_multi_file_reader.cpp, src/iceberg_snapshot_lookup.cpp, src/include/catalog_api.hpp, src/include/iceberg_options.hpp, src/include/metadata/iceberg_table_metadata.hpp, src/include/storage/irc_table_entry.hpp, src/include/storage/irc_table_set.hpp, src/metadata/iceberg_table_metadata.cpp, src/storage/irc_schema_entry.cpp, src/storage/irc_table_entry.cpp, src/storage/irc_table_set.cpp, test/sql/local/iceberg_scans/iceberg_scan_schema_evo_timetravel.test, test/sql/local/irc/iceberg_catalog_read.test
This PR fixes #252 
This PR ended up doing a bunch of clean up to get this working correctly
We do away with the `IRCAPITable` struct, as it wasn't adding any value
The `IRCTableSet` entries are now `IcebergTableInformation`, which now holds the `unique_ptr<ICTableEntry>`, 1 for every schema that the table has.
`LoadEntries` no longer creates a `unique_ptr<ICTableEntry>`, this used to make a dummy, so we had something to return as a "candidate" for error messages, retrieved with `Scan`.
Instead we only create the entries with `FillEntry`, and `Scan` now calls `FillEntry`, to keep the same candidate information.
=> [REST Catalog] Return catalog entry with the correct table schema for time travel queries

src/iceberg_value.cpp, test/sql/local/schema_evolve_float_to_double.test, test/sql/local/schema_evolve_int_to_bigint.test
Apply the https://iceberg.apache.org/spec/#schema-evolution inference rules
Working on this, I did notice that we don't have a test for schema evolving `date` -> `timestamp`.
I believe this is because spark doesn't support it, we can probably create a persistent this for this with `pyiceberg` ?
Despite this, I have implemented the inference rules for that schema evolution.
=> Apply the schema evolution inference rules deserializing bound values

src/catalog_api.cpp, src/include/catalog_api.hpp, src/include/storage/irc_catalog.hpp, src/include/storage/irc_schema_set.hpp, src/include/storage/irc_transaction.hpp, src/storage/irc_catalog.cpp, src/storage/irc_schema_set.cpp, src/storage/irc_transaction.cpp, test/sql/local/irc/iceberg_catalog_eager_refresh.test, test/sql/local/irc/iceberg_catalog_read.test
This PR fixes #247 
Previously, the schemas and tables would only hit the REST endpoints once, to get the state of the Catalog at that point in time.
No refresh would ever be made.
This PR changes this behavior to hit the REST endpoints once **per transaction**
We realize this is a little too eager, and we will make further improvements to this to cache existing tables/schemas preventing unnecessary http requests.
But for now we make the choice to value correctness over performance in this case.
=> [Dev][Caching] Move the `IRCSchemaSet` to the `IRCTransaction`, so it gets refreshed with every new transaction

CMakeLists.txt, scripts/lakekeeper/auth_type_none/create-demo-warehouse.json, scripts/lakekeeper/auth_type_none/docker-compose.yaml, scripts/lakekeeper/auth_type_none/populate.py, src/common/api_utils.cpp, src/include/storage/authorization/none.hpp, src/include/storage/irc_authorization.hpp, src/storage/authorization/none.cpp, src/storage/irc_authorization.cpp, src/storage/irc_catalog.cpp, test/sql/local/irc/errors/wrong_authorization_type.test, test/sql/local/irc/test_lakekeeper_none.test
This PR adds the ability to connect to Lakekeeper with `LAKEKEEPER_CATALOGS_DEMO_AUTHORIZATION_TYPE=none`
Thanks to https://github.com/duckdb/duckdb/discussions/17813 for motivating and providing a working reproducer.
As a side effect of working on this, I discovered that this connection is already possible on `main` (I think v1.3.0 release as well) using:
```sql
attach 'demo' as my_datalake (
type ICEBERG,
ENDPOINT 'http://localhost:8181/catalog',
TOKEN ''
);
```
By supplying the TOKEN, we won't try to hit any authorization server, the only functional difference is that with this branch we won't send a Bearer token with the request, whereas on `main` we do send a Bearer token, but that should be ignored anyways if the authorization type is None on the Catalog server.
=> Add support for `AUTHORIZATION_TYPE 'none'` (Nessie, Lakekeeper (in no-auth mode))

src/aws.cpp, test/sql/cloud/s3tables/test_logging_aws.test
Very crude implementation, but we need to create a GetRequestInfo from an AWS request object so we could log the request info. This gets that working in a way 
fixes https://github.com/duckdb/duckdb-iceberg/issues/263
=> Reenable logging of IRC requests to AWS catalogs

src/common/api_utils.cpp, src/include/api_utils.hpp, src/storage/authorization/oauth2.cpp
This PR likely fixes #300 
From https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1:
> The authorization server MUST support the HTTP Basic
authentication scheme for authenticating clients that were issued a
client password.
=> [Dev][OAuth2] Use the `Authorization` header instead of embedding the client_id+client_secret in the POST body.

src/storage/irc_table_set.cpp, test/sql/local/irc/test_show_table_duplicates.test
This PR fixes #329 
We were invoking the callback for every schema version, when we should only be invoking it once, with the latest schema version.
=> Fix duplicate entries reported in `ICTableSet::Scan`

vcpkg.json
Previous approach had some problems while in the context of duckdb/duckdb Linux CI.
This seems the most safe change for today, to be revisited.
=> Move back to vcpkg-duckdb-ports

test/sql/local/iceberg_scans/iceberg_metadata.test, test/sql/local/iceberg_scans/iceberg_scan.test, test/sql/local/iceberg_scans/uuid_type.test
Those will prevent iceberg from passing autoloading tests, meaning it will not be deployed nightly.
=> Fixup tests/ 2

src/storage/authorization/sigv4.cpp
I met a compilation issue
```sh
/tmp/duckdb-iceberg/src/storage/authorization/sigv4.cpp: In static member function ‘static duckdb::unique_ptr<duckdb::IRCAuthorization> duckdb::SIGV4Authorization::FromAttachOptions(duckdb::IcebergAttachOptions&)’:
/tmp/duckdb-iceberg/src/storage/authorization/sigv4.cpp:53:16: error: could not convert ‘result’ from ‘unique_ptr<duckdb::SIGV4Authorization,default_delete<duckdb::SIGV4Authorization>,[...]>’ to ‘unique_ptr<duckdb::IRCAuthorization,default_delete<duckdb::IRCAuthorization>,[...]>’
53 |         return result;
|                ^~~~~~
|                |
|                unique_ptr<duckdb::SIGV4Authorization,default_delete<duckdb::SIGV4Authorization>,[...]>
[346/845] Building CXX object extension/iceberg/CMakeFiles/iceberg_extension.dir/src/storage/irc …
```
=> Fix compilation

src/storage/iceberg_table_information.cpp, test/sql/cloud/r2_catalog/test_r2_attach_and_read.test
if the provided endpoint starts with https:// set use_ssl to true reg…ardless of path_style_access trye
fixes https://github.com/duckdblabs/duckdb-internal/issues/5407
=> [BUGFIX] use https on r2 gets. Path style access does not mean do not use ssl

.github/workflows/CloudTesting.yml, test/sql/cloud/glue/test_create_table_glue.test, test/sql/cloud/glue/test_direct_keys_glue.test, test/sql/cloud/glue/test_direct_keys_glue_no_endpoint_type.test, test/sql/cloud/glue/test_insert_glue.test, test/sql/cloud/snowflake/test_snowflake.test, test/sql/cloud/snowflake/test_snowflake_s3.test
Add a test for reading from a snowflake open catalog backed by s3. Also fix glue tests
passing CI run here 
https://github.com/duckdb/duckdb-iceberg/actions/runs/17236841104
=> Add s3 snowflake and fix glue tests

.github/workflows/CloudTesting.yml, extension_config.cmake, src/iceberg_functions/iceberg_avro_multi_file_reader.cpp, src/iceberg_functions/iceberg_multi_file_reader.cpp, src/include/iceberg_avro_multi_file_reader.hpp, src/include/iceberg_multi_file_reader.hpp, src/storage/iceberg_table_information.cpp, test/sql/cloud/glue/test_create_table_glue.test, test/sql/cloud/glue/test_direct_keys_glue.test, test/sql/cloud/glue/test_direct_keys_glue_no_endpoint_type.test, test/sql/cloud/glue/test_insert_glue.test, test/sql/cloud/snowflake/test_snowflake.test, test/sql/cloud/snowflake/test_snowflake_s3.test
Merges things in v1.3-ossivalis to v1.4 and also fixing code in v1.4 so that it can build with duckdb-main
=> Update v1.4 andium

scripts/data_generators/tests/table_with_deletes/__init__.py, scripts/data_generators/tests/test_not_null/__init__.py, scripts/data_generators/tests/test_not_null/q00.sql, scripts/data_generators/tests/test_not_null/q01.sql, src/storage/create_table/iceberg_create_table_request.cpp, src/storage/iceberg_insert.cpp, test/sql/local/irc/create/test_create_table_not_null.test, test/sql/local/irc/insert/test_insert_into_null_columns.test
Tests structs and primitive types. Have not yet figured out how create a map type with a `NOT NULL` requirement for lists and maps. I've stepped through the code though, and we should still throw an error in these cases
=> Disable inserting NULL into columns marked NOT NULL

src/storage/irc_catalog.cpp, src/storage/irc_schema_entry.cpp, test/sql/local/irc/test_cascade.test
This PR fixes https://github.com/duckdblabs/duckdb-internal/issues/5754
The actual functionality can be implemented later, for now I think it's important to block off all avenues that are not behaving correctly
=> Disable drops of all types with `CASCADE` for now

extension_config.cmake, src/avro_scan.cpp, src/iceberg_extension.cpp, src/storage/table_update/iceberg_add_snapshot.cpp
Just load avro on extension load
Could supersede https://github.com/duckdb/duckdb-iceberg/pull/452, but want to check if conflicts with spatial are resolved first. Status of that is in https://github.com/Tmonster/duckdb/pull/247
=> Load avro on extension load

extension_config.cmake, src/storage/table_update/iceberg_add_snapshot.cpp
Interesting bug when creating a table, since no snapshot exists, the block 
```
if (current_snapshot) {
...
auto scan = make_uniq<AvroScan>("IcebergManifestList", context, manifest_list_path);
...
}
```
at IRCTransaction::GettransactionRequest is never hit. Which also means avro has not been loaded (since we also have not read any tables yet).
Then when we create the update, we try to get the copy function for avro, but avro has not yet been loaded. 
Not sure if this is the best fix. I remember we wanted to load avro on extension load, but there were conflicts with spatial. @Maxxen do you know if these are fixed yet? 
Otherwise I think this should be pretty safe for now.
fixes https://github.com/duckdb/duckdb-iceberg/issues/382
=> load avro when committing first snapshot

src/iceberg_manifest.cpp, src/include/storage/iceberg_table_update.hpp, src/include/storage/irc_table_set.hpp, src/include/storage/table_update/iceberg_add_snapshot.hpp, src/storage/iceberg_insert.cpp, src/storage/iceberg_table_information.cpp, src/storage/iceberg_transaction_data.cpp, src/storage/irc_schema_entry.cpp, src/storage/irc_table_set.cpp, src/storage/irc_transaction.cpp, src/storage/table_update/iceberg_add_snapshot.cpp, test/sql/local/irc/create/test_create_table_as.test, test/sql/local/irc/test_create_if_not_exists.test
This PR fixes https://github.com/duckdblabs/duckdb-internal/issues/5755
We had an assertion that WriteToFile was never called with a snapshot with no datafiles, but this was never ensured. Now it is. Because of this I've changed how the "SetSnapshotRefUpdate" update is made.
As part of testing this, I noticed `IF NOT EXISTS` was being ignored, so I fixed that and added a test for it.
=> Support `CREATE IF NOT EXISTS`, and fix an issue causing empty snapshots to be created

.github/workflows/MainDistributionPipeline.yml, extension_config.cmake, src/iceberg_functions/iceberg_to_ducklake.cpp, test/sql/iceberg_to_ducklake.test, test/sql/iceberg_to_ducklake.test_slow
Added a test where `iceberg_to_ducklake` is used on the entire generated catalog of tests, and (pretty much) all tables are compared against each other:
```sql
query I rowsort expected_res
select * from my_datalake.default.${table_name}
----
query I rowsort expected_res
select * from my_ducklake.default.${table_name}
----
```
=> Update `iceberg_to_ducklake` for DuckLake v0.3, add/improve tests

src/aws.cpp, src/catalog_api.cpp, test/sql/cloud/glue/test_create_table_glue.test, test/sql/cloud/glue/test_direct_keys_glue.test, test/sql/cloud/glue/test_direct_keys_glue_no_endpoint_type.test, test/sql/cloud/glue/test_glue.test, test/sql/cloud/glue/test_insert_glue.test, test/sql/cloud/r2_catalog/test_r2_attach_and_read.test, test/sql/cloud/r2_catalog/test_r2_create_table.test, test/sql/cloud/r2_catalog/test_r2_inserts.test, test/sql/cloud/r2_catalog/test_r2_pagination.test, test/sql/cloud/s3tables/test_logging_aws.test, test/sql/cloud/test_aws_secret_type.test, test/sql/cloud/test_glue_catalog_with_other_tables.test, test/sql/cloud/test_multiple_catalogs.test, test/sql/cloud/test_use.test
AWS requests would log every request as a GET request. This was incorrect and has now been fixed. 
Also, when running `VerifyNamespaceExistence`, we would only return false if the response was 404. Via cloud testing I have found that some other catalogs return other responses. To avoid surfacing unnecessary http response codes to users, I have decided to expand the scope of what responses merit a logical "This table does not exist" response. 
I have noticed in particular with the Glue catalog that responses are inconsistent with what the iceberg rests api spec defined.
Also added `set ignore_error_messages` for a lot more of the cloud tests.
=> Fix Cloud tests. Modify what responses to `/namespaces` return false

test/sql/cloud/s3tables/test_logging_aws.test, test/sql/cloud/s3tables/test_timeout_aws.test
Fix some cloud tests. We now verify namespaces with a GET (unless the supported urls returns that a  HEAD request can be used)
Need to fix http timeouts for values < 0
=> Fix cloud tests
